name: "in-toto ResourceDescriptor generator"
description: "Generates an in-toto ResourceDescriptor for a local file or remote resource"
inputs:
  is-file:
    description: "Flag indicating whether the resource is a local file or remote. Default is `is-file=true`."
    required: false
    default: 'true'
  name:
    description: "The name of the resource file."
    required: true
  path:
    description: "The path to the resource file. Defaults to GITHUB_WORKSPACE."
    required: false
    default: "$GITHUB_WORKSPACE"
  uri:
    description: "The URI of the remote resource."
    required: false
    default: "https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
  digest:
    description: "The digest associated with the remote resource (hex-encoded)"
    required: false
    default: ""
  hash-alg:
    description: "The hash algorithm used to compute the digest associated with the remote resource."
    required: false
    default: "sha256"
  location:
    description: "The download location of the file"
    required: false
    default: "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
  media-type:
    description: "The media type of the file"
    required: false
    default: "text/plain"
  rd-name:
    description: "The name of the output ResourceDescriptor file. The file must have the .json extension."
    required: true
  rd-path:
    description: "The path to save the generated descriptor"
    default: "$GITHUB_WORKSPACE/temp"
outputs:
  file-rd-name:
    description: "Filename of the generated ResourceDescriptor"
    value: ${{ steps.scai-gen-rd-file.outputs.rd-name }}
  remote-rd-name:
    description: "Filename of the generated ResourceDescriptor"
    value: ${{ steps.scai-gen-rd-remote.outputs.rd-name }}

runs:
  using: "composite"
  steps:
    - name: Run scai-gen rd file
      id: scai-gen-rd-file
      if: ${{ inputs.is-file == 'true' }}
      shell: bash
      run: |
        mkdir -p ${{ inputs.rd-path }}
        scai-gen rd file -n ${{ inputs.name }} -l ${{ inputs.location }} -t ${{ inputs.media-type }} -o ${{ inputs.rd-path }}/${{ inputs.rd-name }} ${{ inputs.path }}/${{ inputs.name }}
        echo "rd-name=${{ inputs.rd-path }}/${{ inputs.rd-name }}" >> "$GITHUB_OUTPUT"

    - name: Run scai-gen rd remote
      id: scai-gen-rd-remote
      if: ${{ inputs.is-file == 'false' }}
      shell: bash
      run: |
        mkdir -p ${{ inputs.rd-path }}
        scai-gen rd remote -n ${{ inputs.name }} -d ${{ inputs.digest }} -g ${{ inputs.hash-alg }} -o ${{ inputs.rd-path }}/${{ inputs.rd-name }} ${{ inputs.uri }}
        echo "rd-name=${{ inputs.rd-path }}/${{ inputs.rd-name }}" >> "$GITHUB_OUTPUT"
