name: Run Go checks
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'scai-gen/**'
  # Want to trigger these tests whenever the Go CLI or
  # APIs are modified
  pull_request:
      paths:
          - 'scai-gen/**'
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.20.x
      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
